FROM openjdk-11

# Create app directory
WORKDIR /main/java


COPY ./bluerentalcars-frontend/package*.json ./

RUN yarn install

# copy all files into the image
COPY ./bluerentalcars-frontend/ .

EXPOSE 3000

CMD ["yarn", "run", "start"]